//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaySpringApp.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int DonationId { get; set; }
        public System.DateTime DonationDate { get; set; }
        public byte DonationType { get; set; }
        public int DonorId { get; set; }
        public byte PaymentType { get; set; }
        public byte CurrencyId { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Donor Donor { get; set; }
    }
}
